### ISSUE TITLE
Error: error sending request for url (https://cdn.jsdelivr.net/npm/vega@5)

### ISSUE THREAD

**Issue by sharkLoc** [alignoth/alignoth#241]
Error: error sending request for url (https://cdn.jsdelivr.net/npm/vega@5)

Caused by:
    0: client error (Connect)
    1: tcp connect error: Connection timed out (os error 110)
    2: Connection timed out (os error 110)

**Comment by fxwiegand** [comment]
Hello @sharkLoc 

I cannot seem to recreate this right now. Was this occurring persistently or just a one off? It could well be that the can from jsdeliver just had an issue for a minute.

**Comment by sharkLoc** [comment]
occurring persistently

**Comment by fxwiegand** [comment]
Are you running this on your local machine? If you're doing that did you try if you can reach the url of the cdn with your browser for example?

**Comment by sharkLoc** [comment]
maybe network error
